# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import les.mp_model.mp_model_pb2
import les.decomposers.decomposers_pb2
import les.backend_solvers.backend_solvers_pb2
import les.solution_tables.solution_tables_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='les/drivers/drivers.proto',
  package='les.drivers',
  serialized_pb='\n\x19les/drivers/drivers.proto\x12\x0bles.drivers\x1a\x1bles/mp_model/mp_model.proto\x1a!les/decomposers/decomposers.proto\x1a)les/backend_solvers/backend_solvers.proto\x1a)les/solution_tables/solution_tables.proto\"\xf1\x01\n\x10\x44riverParameters\x12=\n\x06\x64river\x18\x01 \x02(\x0e\x32\x13.les.drivers.Driver:\x18LOCAL_ELIMINATION_DRIVER\x12\x42\n\x16\x64\x65\x66\x61ult_backend_solver\x18\x02 \x01(\x0e\x32\".les.backend_solvers.BackendSolver\x12Z\n#local_elimination_driver_parameters\x18\x03 \x01(\x0b\x32-.les.drivers.LocalEliminationDriverParameters\"\xb7\x02\n LocalEliminationDriverParameters\x12$\n\x18max_num_shared_variables\x18\x01 \x01(\x03:\x02\x31\x30\x12R\n\ndecomposer\x18\x02 \x01(\x0e\x32\x1b.les.decomposers.Decomposer:!QUASIBLOCK_FINKELSTEIN_DECOMPOSER\x12Q\n\x0esolution_table\x18\x03 \x01(\x0e\x32\".les.solution_tables.SolutionTable:\x15SQLITE_SOLUTION_TABLE\x12\x46\n\x1arelaxation_backend_solvers\x18\x04 \x03(\x0e\x32\".les.backend_solvers.BackendSolver*&\n\x06\x44river\x12\x1c\n\x18LOCAL_ELIMINATION_DRIVER\x10\x00:^\n\x11\x64river_parameters\x12$.les.mp_model.OptimizationParameters\x18\x64 \x01(\x0b\x32\x1d.les.drivers.DriverParameters')

_DRIVER = descriptor.EnumDescriptor(
  name='Driver',
  full_name='les.drivers.Driver',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LOCAL_ELIMINATION_DRIVER', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=750,
  serialized_end=788,
)


LOCAL_ELIMINATION_DRIVER = 0

DRIVER_PARAMETERS_FIELD_NUMBER = 100
driver_parameters = descriptor.FieldDescriptor(
  name='driver_parameters', full_name='les.drivers.driver_parameters', index=0,
  number=100, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_DRIVERPARAMETERS = descriptor.Descriptor(
  name='DriverParameters',
  full_name='les.drivers.DriverParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='driver', full_name='les.drivers.DriverParameters.driver', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='default_backend_solver', full_name='les.drivers.DriverParameters.default_backend_solver', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='local_elimination_driver_parameters', full_name='les.drivers.DriverParameters.local_elimination_driver_parameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=193,
  serialized_end=434,
)


_LOCALELIMINATIONDRIVERPARAMETERS = descriptor.Descriptor(
  name='LocalEliminationDriverParameters',
  full_name='les.drivers.LocalEliminationDriverParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='max_num_shared_variables', full_name='les.drivers.LocalEliminationDriverParameters.max_num_shared_variables', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='decomposer', full_name='les.drivers.LocalEliminationDriverParameters.decomposer', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='solution_table', full_name='les.drivers.LocalEliminationDriverParameters.solution_table', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='relaxation_backend_solvers', full_name='les.drivers.LocalEliminationDriverParameters.relaxation_backend_solvers', index=3,
      number=4, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=437,
  serialized_end=748,
)

_DRIVERPARAMETERS.fields_by_name['driver'].enum_type = _DRIVER
_DRIVERPARAMETERS.fields_by_name['default_backend_solver'].enum_type = les.backend_solvers.backend_solvers_pb2._BACKENDSOLVER
_DRIVERPARAMETERS.fields_by_name['local_elimination_driver_parameters'].message_type = _LOCALELIMINATIONDRIVERPARAMETERS
_LOCALELIMINATIONDRIVERPARAMETERS.fields_by_name['decomposer'].enum_type = les.decomposers.decomposers_pb2._DECOMPOSER
_LOCALELIMINATIONDRIVERPARAMETERS.fields_by_name['solution_table'].enum_type = les.solution_tables.solution_tables_pb2._SOLUTIONTABLE
_LOCALELIMINATIONDRIVERPARAMETERS.fields_by_name['relaxation_backend_solvers'].enum_type = les.backend_solvers.backend_solvers_pb2._BACKENDSOLVER
DESCRIPTOR.message_types_by_name['DriverParameters'] = _DRIVERPARAMETERS
DESCRIPTOR.message_types_by_name['LocalEliminationDriverParameters'] = _LOCALELIMINATIONDRIVERPARAMETERS

class DriverParameters(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DRIVERPARAMETERS
  
  # @@protoc_insertion_point(class_scope:les.drivers.DriverParameters)

class LocalEliminationDriverParameters(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALELIMINATIONDRIVERPARAMETERS
  
  # @@protoc_insertion_point(class_scope:les.drivers.LocalEliminationDriverParameters)

driver_parameters.message_type = _DRIVERPARAMETERS
les.mp_model.mp_model_pb2.OptimizationParameters.RegisterExtension(driver_parameters)
# @@protoc_insertion_point(module_scope)
