# Copyright (c) 2012 Alexander Sviridenko

LES_HOME_PATH = $(dir $(lastword $(MAKEFILE_LIST)))
LES_LIB_DIR_PATH = $(LES_HOME_PATH)/lib

LES_LIB_FILE_NAME = libles.so
LES_LIB_FILE_PATH = $(LES_LIB_DIR_PATH)/$(LES_LIB_FILE_NAME)

COINOR_HOME_DIR_PATH = /home/d2rk/lib/SYMPHONY
COINOR_INCLUDE_DIR_PATH = $(COINOR_HOME_DIR_PATH)/include
COINOR_LIB_DIR_PATH = $(COINOR_HOME_DIR_PATH)/lib
COINOR_LIB_FLAGS = -L$(COINOR_LIB_DIR_PATH) -lCoinUtils

LES_INCLUDE_FLAGS = -I$(LES_HOME_PATH) -I$(COINOR_INCLUDE_DIR_PATH)
LES_LIB_FLAGS = -L$(LES_LIB_DIR_PATH) -lles $(COINOR_LIB_FLAGS)
