LES_HOME_PATH = $(dir $(lastword $(MAKEFILE_LIST)))
LES_LIB_PATH = $(LES_HOME_PATH)/lib

SYMPHONY_HOME_PATH = /home/d2rk/lib/SYMPHONY
SYMPHONY_INCLUDE_PATH = $(SYMPHONY_HOME_PATH)/include

LES_INCLUDE_FLAGS = -I$(LES_HOME_PATH) -I$(SYMPHONY_INCLUDE_PATH)
LES_LIB_FLAGS = -L$(LES_LIB_PATH) $(SYMPHONY_LIB_PATH) -lles -Wl,--rpath -Wl,$(LES_LIB_PATH)