# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import les.mp_model.mp_model_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='les/executors/executors.proto',
  package='les.executors',
  serialized_pb='\n\x1dles/executors/executors.proto\x12\rles.executors\x1a\x1bles/mp_model/mp_model.proto\"O\n\x12\x45xecutorParameters\x12\x39\n\x08\x65xecutor\x18\x01 \x02(\x0e\x32\x17.les.executors.Executor:\x0e\x44UMMY_EXECUTOR*3\n\x08\x45xecutor\x12\x12\n\x0e\x44UMMY_EXECUTOR\x10\x00\x12\x13\n\x0fTHREAD_EXECUTOR\x10\x01:d\n\x13\x65xecutor_parameters\x12$.les.mp_model.OptimizationParameters\x18\x66 \x01(\x0b\x32!.les.executors.ExecutorParameters')

_EXECUTOR = descriptor.EnumDescriptor(
  name='Executor',
  full_name='les.executors.Executor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='DUMMY_EXECUTOR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='THREAD_EXECUTOR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=158,
  serialized_end=209,
)


DUMMY_EXECUTOR = 0
THREAD_EXECUTOR = 1

EXECUTOR_PARAMETERS_FIELD_NUMBER = 102
executor_parameters = descriptor.FieldDescriptor(
  name='executor_parameters', full_name='les.executors.executor_parameters', index=0,
  number=102, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_EXECUTORPARAMETERS = descriptor.Descriptor(
  name='ExecutorParameters',
  full_name='les.executors.ExecutorParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='executor', full_name='les.executors.ExecutorParameters.executor', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=77,
  serialized_end=156,
)

_EXECUTORPARAMETERS.fields_by_name['executor'].enum_type = _EXECUTOR
DESCRIPTOR.message_types_by_name['ExecutorParameters'] = _EXECUTORPARAMETERS

class ExecutorParameters(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTORPARAMETERS
  
  # @@protoc_insertion_point(class_scope:les.executors.ExecutorParameters)

executor_parameters.message_type = _EXECUTORPARAMETERS
les.mp_model.mp_model_pb2.OptimizationParameters.RegisterExtension(executor_parameters)
# @@protoc_insertion_point(module_scope)
