# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import les.mp_model.mp_model_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='les/solution_tables/solution_tables.proto',
  package='les.solution_tables',
  serialized_pb='\n)les/solution_tables/solution_tables.proto\x12\x13les.solution_tables\x1a\x1bles/mp_model/mp_model.proto**\n\rSolutionTable\x12\x19\n\x15SQLITE_SOLUTION_TABLE\x10\x00')

_SOLUTIONTABLE = descriptor.EnumDescriptor(
  name='SolutionTable',
  full_name='les.solution_tables.SolutionTable',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SQLITE_SOLUTION_TABLE', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=95,
  serialized_end=137,
)


SQLITE_SOLUTION_TABLE = 0



# @@protoc_insertion_point(module_scope)
